import { Inter, Nunito } from "next/font/google";
import "./globals.css";

const inter = Nunito({ subsets: ["latin"],weight: "400" });

export const metadata = {
  title: "WeBuzz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
